### ISSUE TITLE
The package does not work with RN 0.29

### ISSUE THREAD

**Issue by alexHlebnikov** [lucasferreira/react-native-android-permissions#5]
Hi. 

```
import android.app.Application;
import android.util.Log;

import com.burnweb.rnpermissions.RNPermissionsPackage;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends Application implements ReactApplication {

    private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
        @Override
        protected boolean getUseDeveloperSupport() {
            return BuildConfig.DEBUG;
        }

        @Override
        protected List<ReactPackage> getPackages() {
            return Arrays.<ReactPackage>asList(
                new MainReactPackage(),
                new RNPermissionsPackage()
            );
        }

        @Override
        public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
            RNPermissionsPackage.onRequestPermissionsResult(requestCode, permissions, grantResults); // very important event callback
            super.onRequestPermissionsResult(requestCode, permissions, grantResults);
        }
    };

    @Override
    public ReactNativeHost getReactNativeHost() {
        return mReactNativeHost;
    }
}
```

I've got some errors with this package in Android Studio on RN 0.29:
`error: method does not override or implement a method from a supertype`
and 
`error: cannot find symbol method onRequestPermissionsResult(int,String[],int[])`

With RN 0.28 everything works fine. 
I think it's because in RN 0.29 there are breaking changes on Android - https://github.com/facebook/react-native/releases/tag/v0.29.0

How to fix my problem?

**Comment by alexHlebnikov** [comment]
So, I've found the solution: 

I'll add a PR for the correct installation instructions for RN 0.29
Here is PR: https://github.com/lucasferreira/react-native-android-permissions/pull/6
